[package]
name = "task-5"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
once_cell = "1.21.3"
pyo3 = { version = "0.24.1", features = ["auto-initialize"] }
stop-words = { version = "0.8.1", features = ["nltk"] }
